const PlanActionTypes = {
    UPDATE_PLAN_PROPS: "UPDATE_PLAN_PROPS",
    SET_PLAN_ELEMENTS: "SET_PLAN_ELEMENTS",
    SET_PLAN_CURSOR_POS: "SET_PLAN_CURSOR_POS",
    SET_PLAN_ELEMENTS_RECORDS: "SET_PLAN_ELEMENTS_RECORDS",
    SET_PLAN_MODE: "SET_PLAN_MODE",
    // SET_PLAN_IS_SCALING: "SET_PLAN_IS_SCALING",
    SET_PLAN_IS_DRAGGING: "SET_PLAN_IS_DRAGGING",
    ADD_PLAN_ELEMENT: "ADD_PLAN_ELEMENT",
    UPDATE_PLAN_ELEMENT: "UPDATE_PLAN_ELEMENT",
    REMOVE_PLAN_ELEMENT: "REMOVE_PLAN_ELEMENT",
    SET_SELECTING_PLAN_ELEMENT: "SET_SELECTING_PLAN_ELEMENT",
    SET_UNSELECT_ALL_ON_PLAN_MOUSE_UP: "SET_UNSELECT_ALL_ON_PLAN_MOUSE_UP",
    SET_ADDING_POINT_LINE_ID_POINT_ID: "SET_ADDING_POINT_LINE_ID_POINT_ID",
    SET_LINE_TO_ADD: "SET_LINE_TO_ADD",
    SET_PLAN_ELEMENT_SHEET_DATA: "SET_PLAN_ELEMENT_SHEET_DATA",
    SET_TEST_POINTS: "SET_TEST_POINTS",
    SET_MAGNET_DATA: "SET_MAGNET_DATA",
    SET_ADD_SEG_SESSION: "SET_ADD_SEG_SESSION",
    SET_PLAN_ELEMENT_SNAPSHOT: "SET_PLAN_ELEMENT_SNAPSHOT",
  };
    
  export default PlanActionTypes;
    