const PlanActionTypes = {
    UPDATE_PLAN_PROPS: "UPDATE_PLAN_PROPS",
    SET_PLAN_ELEMENTS: "SET_PLAN_ELEMENTS",
    ADD_PLAN_ELEMENT: "ADD_PLAN_ELEMENT",
    UPDATE_PLAN_ELEMENT: "UPDATE_PLAN_ELEMENT",
    REMOVE_PLAN_ELEMENT: "REMOVE_PLAN_ELEMENT",
    SET_SELECTING_PLAN_ELEMENT: "SET_SELECTING_PLAN_ELEMENT",
    SET_UNSELECT_ALL_ON_PLAN_MOUSE_UP: "SET_UNSELECT_ALL_ON_PLAN_MOUSE_UP"
  };
    
  export default PlanActionTypes;
    